### ISSUE TITLE
Deployment + Pipelines at Ensuresec Platform VM

### ISSUE THREAD

**Issue by dominic22** [iotaledger/integration-services#250]
- deploy new version of the Integration Services
- eventually adjust deployment pipeline
- connect to VM an verify if Server Identity was created successfully

**Comment by mastrogiovanni** [comment]
References: Sadjy, Razvan

**Comment by mastrogiovanni** [comment]
https://github.com/marketplace/actions/kubectl-aws-eks

**Comment by dominic22** [comment]
we decided to not update the simavi vm.
