### ISSUE TITLE
Mongo DB password setup

### ISSUE THREAD

**Issue by dominic22** [iotaledger/integration-services#254]

**Comment by dominic22** [comment]
@mastrogiovanni yes it looks like you already tackled this by having the password files for the mongodb when starting kubernetes. I understood it as you wanted to tackle this later, so if this is covered we can delete this ticket or move it also to testing an reference it at the other ticket

**Comment by mastrogiovanni** [comment]
In kubernetes task we just added a mongodb username/password/database creation: I don't know if you need to inject schemas and/or indexes after the service startup. The two thinks should be splitted: in mongodb deployent creation of admin user and database, while collection and indexes must be created on service startup (if missing)

**Comment by mastrogiovanni** [comment]
This task is obsolete since in case of already created database, the API is already able to setup its data.
I'm closing it
