### ISSUE TITLE
Small cleanups

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/integration-services#282]
This is a simple task to discuss/request cleanup

- EXPLORER is more needed?
- API_VERSION is already exposed (in the right manner) as endpoint (/api/v1/...) can it be removed?
- NETWORK is needed anymore?
- PERMANODE is needed?

/info dump a log: remove it since info is used as healthcheck and this will produce a lot of logs

open api validation (like this service: https://italia.github.io/api-oas-checker/) show many unused schema and other problems in swagger: this can make client creation difficult

**Comment by dominic22** [comment]
Removed obsolete vars.

PERMANODE is needed?
Yes is needed to request data from a permanode

API_VERSION is already exposed (in the right manner) as endpoint (/api/v1/...) can it be removed?
We use api version in our url if like the v0.1 in https://ensuresec.solutions.iota.org/api/v0.1/identities/create
