### ISSUE TITLE
Bump up identity dependency to version 0.6.0

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/integration-services#287]
Identity 0.5.0 will bring versioned identities but all previous identities won't be compatible with this sdk anymore!

Need to wait for the release of 0.5.0

Let's clarify that data on the ensuresec platform could be wiped out because the old identities and data are no more compatible.

It this is not possible, some method to manage both world (new and old identities) must be defined.

Tasks:
- Upgrade identity library
- Check all endpoint and methods regarding identities
- Update wiki in case it applies.

**Comment by dominic22** [comment]
moved to backlog since we need to wait for new identity release.

**Comment by dominic22** [comment]
reduced amount since created and closed #86 to better track effort during sprint
