### ISSUE TITLE
CityxChange SLU authenticity

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/integration-services#322]
https://docs.google.com/document/d/10Cuu7Ql35J0I7Ctrnf8s1JYxir_I4__GRk2EX15rBEQ/edit

**Comment by DuncanMain** [comment]
https://docs.google.com/document/d/10Cuu7Ql35J0I7Ctrnf8s1JYxir_I4__GRk2EX15rBEQ/edit#
