### ISSUE TITLE
Fix bugs in swagger docs

### ISSUE THREAD

**Issue by Schereo** [iotaledger/integration-services#328]
Buglist:
- **get /identities/search** lists just a single identity as return type not an array as expected (have a look if even IdentySchema is the proper return type, the Service lists User as the return type)
- **get /identities/identity/{identityId}** is missing the  security: BearerAuth: [] annotation
- **post /identities/identity** lists IdentitySchema as the return value but addUser does not return any value
- ** put /identities/identity** type in requestBody IdentitySchema does not match validation rule UpdateIdentityBodySchema also the return type IdentitySchema is not correct, updateUser does not return anything
- **ssi-service getLatestIdentityJson** change return Promise type to LatestIdentityJsonSchema (type has to be created from schema first)
- **get /verification/trusted-roots** replace return type with a schema
- **post /verification/create-credential** return type VerifiableCredentialSchema does not match actual return type VerifiableCredentialJson
- **post /verification/check-credential** replace return type with a schema
- **get /channels/history/{channelAddress}** missing return type of type ChannelData[]
- **post  /channels/validate/{channelAddress}** switch up summary and description
- **get /channel-info/channel/{channelAddress}** fix descriptions, reads weirdly
- **post /subscriptions/authorize/{channelAddress}** return type does not match docs, use schema for return type in code
- **post /subscriptions/authorize/{channelAddress}** description still mentions e-commerce, should be renamed
- **get /identities/search** registration-date is not exact match, the date is greater or equal, fine but missing description for this behaviour and write description for search parameter 'type', the type of the claim is meant here but not clearly stated in the docs
- **get /channel-info/search** takes one additional parameter author-id which is not listed in the swagger docs

**Comment by Schereo** [comment]
Buglist:
- **/identities/search** lists just a single identity as return type not an array as expected

**Comment by dominic22** [comment]
seems to have already been closed with the implementation of the security analysis
