### ISSUE TITLE
Client API for Integration Services (java)

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/integration-services#336]
https://github.com/albydeca/InteractionIOTA

cleanup repository (write README, licensing...)
find a standard way to have methods (create/manage identity and streams)
make repo public
at the end repo should go in iotaledger or iota-community
maven dependency must be published
wiki must be updated to include examples with java client

**Comment by albydeca** [comment]
Hi, thanks for opening this issue. I am Alberto from Gradbase (gradba.se) and I will be leading this effort on our side. The repo at the current link allows basic creation of `Channel`s, `Author`s and `Subscriber`s as well as publishing and retrieving data. The plan is to modify the existing codebase to conform to the Node specification contained in this repo.
