### ISSUE TITLE
IOTA_HORNET_NODE missing in docker-compose.yml

### ISSUE THREAD

**Issue by DocBO** [iotaledger/integration-services#355]
Hi,
in the docker-compose.yml was missing: IOTA_HORNET_NODE: ${IOTA_HORNET_NODE} 

A documentation question: why is even a mongo-init.js there? Do I need to create another db user and for what? As far as I understood the root user is created at startup time.

**Comment by dominic22** [comment]
Sorry for late notice. We've added the IOTA_HORNET_NODE in the docker-compose. The mongo-init will create you a user in the db which you can use for the IS.
