### ISSUE TITLE
Dig_it Kafka Connector

### ISSUE THREAD

**Issue by DuncanMain** [iotaledger/integration-services#371]
- we will get a Kafka API to connect and write all data in the Streams
- we need to interact with this API in NodeJS 
- one channel to be created to write all data
- later to see if there are separate channels to be created per tag 

# Resources

Example for nodeJS usage of Kafka queue:
- how to create a Kafka queue on Kubernetes for testing
- how interact with Kafka queue in nodeJS
https://iotafoundation.atlassian.net/l/c/V50as788

**Comment by nenadgligoric** [comment]
Does not allow me to edit

- we will get a Kafka API to connect and write all data in the Streams
- we need to interact with this API in NodeJS 
- one channel to be created to write all data
- later to see if there are separate channels to be created per tag
