### ISSUE TITLE
WIKI Update Generic project presentaions

### ISSUE THREAD

**Issue by DuncanMain** [iotaledger/integration-services#491]

**Comment by DuncanMain** [comment]
**Presentations**
Add project presentations to: learn --> Media Library --> (new) Project Presentations

[Ensuresec generic presentation](https://docs.google.com/presentation/d/1HVnWNb6WU_68bstrZinUJ6JFHNx7yY3F/edit?usp=sharing&ouid=117843013151042005451&rtpof=true&sd=true)

[CxC generic presentation](https://docs.google.com/presentation/d/1k6ekVe0WhyuouYFXKANolaIaFBTdKbeF/edit?usp=sharing&ouid=117843013151042005451&rtpof=true&sd=true)

[Secant generic presentation](https://docs.google.com/presentation/d/16izrquGD-4LqVtZELSJeA2RSZImBvocm/edit?usp=sharing&ouid=117843013151042005451&rtpof=true&sd=true)

**Bug statement**
Add a statement to this page https://wiki.iota.org/integration-services/welcome under the "caution" box at the bottom. Please also place this in a yellow warning box with a wee bug image and "bug reporting" as the heading

 "Please report any bugs found whilst engaging with any part of the integration services to [integrations@iota.org]”

**Comment by lucas-tortora** [comment]
@DuncanMain, do we by any chance have videos for these presentations? I think they'd probably reach a broader audience that way.

**Comment by DuncanMain** [comment]
@lucas-tortora No we don't, but.... I think we can export them as vids. I will try.

**Comment by DuncanMain** [comment]
@lucas-tortora Is there any blocker to get these videos uploaded?
