### ISSUE TITLE
Fix merging boards problems

### ISSUE THREAD

**Issue by dominic22** [iotaledger/integration-services#519]
The cloud services board merges several github repositories. We want to have one board with columns to overview all projects inside cloud services.

Currently the tasks in each project does not stick to the correct column in the Integration Services board. Please research and fix this problem so each task is in the correct column.

**Comment by JuriBog** [comment]
The solution for that problem is not included in our Zenhub license. One solution could be "worklfows" but for that we need to split each repo into their own workspace and connect the columns to Cloud Services where we would have  a one-way of control and that seems not  a valid solution for us.
