### ISSUE TITLE
Add private docker repo

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/integration-services#580]
Add build and push on private ECR repo for ssi-bridge, audit-trail-gw and dashboard.
Old "docker hub" actions need to be removed

**Comment by FranCerdan** [comment]
New pipeline added, docker images will be deployed into ECR : `https://eu-west-1.console.aws.amazon.com/ecr/repositories?region=eu-west-1 `

Old git-hub actions disabled at `https://github.com/iotaledger/integration-services/actions`

Todo:
1. Rename repo with "-" not "_"
2. Create script to automatically generate user with permissions over the private repo with a expiration time.
3. Crete how-to of step (2)

**Comment by FranCerdan** [comment]
Done:
1. Crate github action pipeline to deploy images to private ECR
2. Disable old github actions ( docker-hub) 
3. Rename repositories to follow best practice
4. Use iotaledged/aws-kubeclt managed docker image for kubernetes (is-infra repo under blueprint folder)

Todo:
1. Create script to automatically generate user with permissions over the private repo with a expiration time.
2. Crete how-to of step (1)
