### ISSUE TITLE
Investigate create presentation alternative 

### ISSUE THREAD

**Issue by dominic22** [iotaledger/integration-services#677]
Please add result in comments.

Check if we really could:
- also sign the verifiable presentation using our existing sign method and send it to the backend which then publishes it using the identity sdk?

**Comment by JuriBog** [comment]
Added this method in base.ts:

async sign(privateKey: string, data: string){
  const uint8Data = new Uint8Array(Buffer.from(data));
  const signedHash = await ed.sign(uint8Data, privateKey);
  return ed.Signature.fromHex(signedHash).toHex();
}

Tested the method with this code: 

async function signVp() {
  const config: ClientConfig = {
    isGatewayUrl: 'http://localhost:3000',
    apiKey: '1cfa3bce-654d-41f6-a82a-94308dc4adf8',
    apiVersionAuditTrail: ApiVersion.v0_1,
    apiVersionSsiBridge: ApiVersion.v0_2,
    useGatewayUrl: true
  };
  const vp = {
    context: "https://www.w3.org/2018/credentials/v1",
    type: "VerifiablePresentation",
    verifiableCredential: {
      context: "https://www.w3.org/2018/credentials/v1",
      id: "did:iota:G5MfzLpMpRsTtmGochhrbXiSrbTKDvgC5Bgw7HdU85pV",
      type: ["VerifiableCredential", "VerifiedIdentityCredential"],
      credentialSubject:
      {
        id: "did:iota:G5MfzLpMpRsTtmGochhrbXiSrbTKDvgC5Bgw7HdU85pV",
        context: "https://schema.org/",
        familyName: "Engineer",
        givenName: "Test",
        initiator: "did:iota:AUKN9UkJrTGGBcTZiYC3Yg2FLPQWnA11X8z6D6DDn56Y",
        jobTitle: "Software Engineer",
        name: "Test Engineer",
        type: "Person"
      },
      issuer: "did:iota:BPvL2gG71pcNCnqpk1uqFYRK25ELxoVKLDW18reyCnfy",
      issuanceDate: "2022-08-12T12:44:53Z",
      credentialStatus: {
        id: "did:iota:BPvL2gG71pcNCnqpk1uqFYRK25ELxoVKLDW18reyCnfy#signature-bitmap-0",
        type: "RevocationBitmap2022",
        revocationBitmapIndex: "6"
      },
      proof: {
        type: "JcsEd25519Signature2020",
        verificationMethod: "did:iota:BPvL2gG71pcNCnqpk1uqFYRK25ELxoVKLDW18reyCnfy#sign-0",
        signatureValue: "5ch4nJhQEbY21y4zHoPAqTSyoVzXjurFM4xgjQvZPF9EebUB7owHfMxme4wcXdzWiWWjKZv5SDFUm9tzpfQfaKGq"
      }
    },
    holder: "did:iota:G5MfzLpMpRsTtmGochhrbXiSrbTKDvgC5Bgw7HdU85pV",
    proof: {
      type: "JcsEd25519Signature2020",
      verificationMethod: "did:iota:G5MfzLpMpRsTtmGochhrbXiSrbTKDvgC5Bgw7HdU85pV#sign-0",
      signatureValue: "23Tn2vxYHkjgBTFzP1yqXLbz6S5Zb2F6x3uDiDUgH37YNijjoA9dDyMegPCok4bLFcyBk1uMoEcVHKkqjt9gDLB1",
      expires: "2022-08-12T13:38:20Z"
    }
  }
  const identityClient = new IdentityClient(config);

  const decoded = identityClient.getHexEncodedKey('98cXSPbRtUPmWSkNAUvA2MkC1Sb33BTjDj3Ev2UbQYxt')
  const signed = await identityClient.sign(
    decoded,
    JSON.stringify(vp)
  );

  console.log(signed);
}
